config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :authors
  # get '/authors', :to => 'authors#indez'
  root 'authors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ApplicationRecord
	has_and_belongs_to_many :authors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	before_action :set_author, only: [:update, :edit,:delete, :show]

	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
		respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
	end

	def index
		@authors = Author.all
	end

	def update
		respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
	end

	def show
		@author
	end

	def edit

	end

	def delete

	end

	private

		def set_author
			@author = Author.find params["id"]
		end
		
		def author_params
			params.require(:author).permit(:id, :name, book_ids: [])
		end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, only: [:update, :edit,:delete, :show]

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
	end

	def show

	end

	def index
		@books = Book.all
	end

	def update
		respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit

	end

	def delete

	end

	private

		def set_book
			@book = Book.find params["id"]
		end
		
		def book_params
			params.require(:book).permit(:id, :name, author_ids: [])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author, html: { class: "m-t"}) do |f| %>

<div class="field">
  <%= f.label :name %><br />
  <div class="form-group" style="border-left: 3px solid #00a2bd;">
  <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>
</div>

<div class="field">
  <%= f.label :books %><br />
  <div class="form-group" style="border-left: 3px solid #00a2bd;">
  <%= f.collection_select :book_ids, Book.order(:name), :id, :name, {}, {multiple: true, class: "form-control"} %>
  </div>
</div>

<div class="actions">
	<%= f.submit "Create author", class: "btn btn-lg btn-primary btn-block" %>
</div>

<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author information</h1>
<%= render 'form' %>

app/views/authors/index.html.erb
<h1>Listing Authors</h1>
<div class="table-responsive">
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Books</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 

 

  <% @authors.each do |author| %>
    <div class="col-sm-6 col-md-3">
      <div class="">
      
        <tr>
          <td><%= author.name %></td>
          <td><%= author.books.pluck(:name).join(", ") %></td>
          <td><%= link_to "Show", author %></td>
          <td><%= link_to "Edit", edit_author_path(author) %></td>
          <td><%= link_to "Remove", author, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      </div>
    </div>
  <% end %>

</table>
</div>
 
<br>
<%= link_to "New Author", new_author_path %>

app/views/authors/new.html.erb
<h1>Create Author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<h1>Author's Information</h1>

<div class="row">
<div class="field col-sm-6">
  <p>Name</p>
  <div class="form-group">
  	<%= @author.name %>
  </div>
</div>

<div class="field col-sm-6">
  <p>Books</p>
  <div class="form-group">
  	<% @author.books.each do |book| %>
  		<p> <%= book.name %> </p>
  	<% end %>
  </div>
</div>
</div>
<%= link_to 'Edit', edit_author_path(@author) %> |

app/views/books/_form.html.erb
<%= form_for(@book, html: { class: "m-t"}) do |f| %>

<div class="field">
  <%= f.label :name %><br />
  <div class="form-group" style="border-left: 3px solid #00a2bd;">
  <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>
</div>

<div class="field">
  <%= f.label :books %><br />
  <div class="form-group" style="border-left: 3px solid #00a2bd;">
  <%= f.collection_select :author_ids, Author.order(:name), :id, :name, {}, {multiple: true, class: "form-control"} %>
  </div>
</div>

<div class="actions">
	<%= f.submit "Create Book", class: "btn btn-lg btn-primary btn-block" %>
</div>

<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<h1>Listing Books</h1>
 
<div class="table-responsive">
<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @books.each do |book| %>
  <tr>
    <td><%= book.name %></td>
    <td><%= link_to "Show", book %></td>
    <td><%= link_to "Edit", edit_book_path(book) %></td>
    <td><%= link_to "Remove", book, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>
</div>
 
<br>
 
<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<h1>Book's Information</h1>
<div class="dashed"></div>
<div class="row">
<div class="field col-sm-6">
  <p>Name</p>
  <div class="form-group">
  	<%= @book.name %>
  </div>
</div>

<div class="field col-sm-6">
  <p>Books</p>
  <div class="form-group">
  	<% @book.authors.each do |author| %>
  		<p> <%= author.name %> </p>
  	<% end %>
  </div>
</div>
</div>
<%= link_to 'Edit', edit_book_path(@book) %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="content-wrapper">

        <section class="content">
      
          <div class="container-fluid">
    <%= yield %>
    </div>
    </section>
    </div>
  </body>
</html>